/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurent;

import java.awt.Toolkit;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author MOON
 */
public class A_login extends javax.swing.JFrame {

    public Connection conn = null;
    public Statement st;

    /**
     * Creates new form Login
     */
    public A_login() {
        setTitle("Square Food & Restaurent");

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jUsername = new javax.swing.JTextField();
        jPassword = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLog = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCom = new javax.swing.JComboBox<>();
        jBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(672, 384));
        setResizable(false);
        getContentPane().setLayout(null);

        jUsername.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jUsername);
        jUsername.setBounds(480, 100, 170, 30);

        jPassword.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        getContentPane().add(jPassword);
        jPassword.setBounds(480, 150, 170, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 100, 170, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 150, 170, 30);

        jLog.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLog.setText("Log in");
        jLog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogActionPerformed(evt);
            }
        });
        getContentPane().add(jLog);
        jLog.setBounds(560, 280, 90, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(430, 280, 90, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(300, 280, 90, 30);

        jCom.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Type", "Admin", "Employee" }));
        getContentPane().add(jCom);
        jCom.setBounds(530, 200, 110, 30);

        jBackground.setBackground(new java.awt.Color(240, 142, 198));
        jBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurent/restaurant.jpg"))); // NOI18N
        getContentPane().add(jBackground);
        jBackground.setBounds(0, 0, 670, 384);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jUsername.setText(null);
        jPassword.setText(null);
        jCom.setSelectedIndex(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:

        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogActionPerformed
        // TODO add your handling code here:
        String user = jUsername.getText();
        String pass = jPassword.getText();

        try {

            //create a connection
            Class.forName("com.mysql.jdbc.Driver");
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant_management?zeroDateTimeBehavior=convertToNull", "root", "");
            st = conn.createStatement();
            //login
            String query = "select* from admin_login where user_name='" + user + "' and password='" + pass + "'";
            PreparedStatement ps = conn.prepareStatement(query);
            ResultSet result = ps.executeQuery();

            if (result.next()) {
                if (jCom.getSelectedItem() == "Admin") {
                    Admin main = new Admin();
                    main.setTitle("Square Food & Restaurant");
                    main.setVisible(true);

                    jUsername.setText(null);
                    jPassword.setText(null);
                    jCom.setSelectedIndex(0);
                    dispose();

                } else if (jCom.getSelectedItem() == "Employee") {
                    EmployeeHome em = new EmployeeHome();
                    em.setVisible(true);
                    dispose();

                    jUsername.setText(null);
                    jPassword.setText(null);
                    jCom.setSelectedIndex(0);
                    dispose();

                }

            } else {
                
                try {
                    //create a connection
                    /* Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant_management?zeroDateTimeBehavior=convertToNull","root","");
                st=conn.createStatement();*/
                    //login
                    String equery = "select* from employeer_registration where user_name='" + user + "' and password='" + pass + "'";
                    PreparedStatement eps = conn.prepareStatement(equery);
                    ResultSet eresult = eps.executeQuery();

                    if (eresult.next()) {
                        if (jCom.getSelectedItem() == "Employee") {
                            EmployeeHome em = new EmployeeHome();
                            em.setVisible(true);
                            dispose();

                            jUsername.setText(null);
                            jPassword.setText(null);
                            jCom.setSelectedIndex(0);
                            dispose();

                        }
                        else {
                        JOptionPane.showMessageDialog(null, "Invalid Input or type");
                    }
                        st.close();
                        conn.close();

                    } else {
                        JOptionPane.showMessageDialog(null, "Invalid Input or type");
                    }

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, e);
                }
                
            }

        } catch (Exception e) {
            Toolkit.getDefaultToolkit().beep();
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_jLogActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new A_login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jBackground;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox<String> jCom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jLog;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUsername;
    // End of variables declaration//GEN-END:variables
}
