/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurent;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author SYSTEM
 */
public class AdminRegistration extends javax.swing.JInternalFrame {
          public Connection conn=null;
          public Statement st;
    /**
     * Creates new form AdminRegistration
     */
    public AdminRegistration() {
        initComponents();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aUserNotify = new javax.swing.JLabel();
        aNameNotify = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        PassInfo = new javax.swing.JLabel();
        AName = new javax.swing.JTextField();
        AUser = new javax.swing.JTextField();
        APass = new javax.swing.JPasswordField();
        BReset = new javax.swing.JButton();
        BCancel = new javax.swing.JButton();
        BReg = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1112, 685));

        jPanel1.setLayout(null);

        aUserNotify.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.add(aUserNotify);
        aUserNotify.setBounds(480, 360, 300, 20);

        aNameNotify.setBackground(new java.awt.Color(255, 51, 51));
        jPanel1.add(aNameNotify);
        aNameNotify.setBounds(480, 290, 300, 20);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 250, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("User Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(320, 320, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 390, 140, 30);

        PassInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PassInfo.setForeground(new java.awt.Color(255, 153, 0));
        PassInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(PassInfo);
        PassInfo.setBounds(300, 430, 610, 30);

        AName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(AName);
        AName.setBounds(480, 250, 300, 40);

        AUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(AUser);
        AUser.setBounds(480, 320, 300, 40);

        APass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(APass);
        APass.setBounds(480, 390, 300, 40);

        BReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BReset.setText("Reset");
        BReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BResetActionPerformed(evt);
            }
        });
        jPanel1.add(BReset);
        BReset.setBounds(700, 480, 80, 40);

        BCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BCancel.setText("Cancel");
        BCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCancelActionPerformed(evt);
            }
        });
        jPanel1.add(BCancel);
        BCancel.setBounds(403, 480, 80, 40);

        BReg.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BReg.setText("Update Admin");
        BReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRegActionPerformed(evt);
            }
        });
        jPanel1.add(BReg);
        BReg.setBounds(530, 480, 130, 40);

        back.setBackground(new java.awt.Color(255, 51, 51));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurent/Admin Registration back UPDATE.jpg"))); // NOI18N
        jPanel1.add(back);
        back.setBounds(0, 0, 1112, 685);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCancelActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_BCancelActionPerformed

    private void BResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BResetActionPerformed
        AName.setText(null);
        AUser.setText(null);
        APass.setText(null);
        PassInfo.setText(null);
        aUserNotify.setText(null);
           aNameNotify.setText(null);
    }//GEN-LAST:event_BResetActionPerformed

    private void BRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRegActionPerformed
        
       String nme=AName.getText();
       String usr=AUser.getText();
       //username validation
       if(nme.matches("^[a-zA-Z\\s]+")&&usr.matches("^[a-z0-9._-]{3,}$")){

            try{
                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant_management?zeroDateTimeBehavior=convertToNull","root","");
                st=conn.createStatement();
                //JOptionPane.showMessageDialog(null, "Connected");
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
        
        }
        
            

              try {
                     String aname=AName.getText();
                     String auser=AUser.getText();
                     String apass=APass.getText();
                  
                  String sql = "update admin_login set name='"+aname+"'"+ ",user_name='"+auser+"'"+",password='"+apass+"' where admin_id='1'";
                  st.executeUpdate(sql);
                  JOptionPane.showMessageDialog(null, "Admin Updated");
                        
                        //Reset text box
                        AName.setText(null);
                        AUser.setText(null);
                        APass.setText(null);
                        
                        //close connection
                  st.close();
                  conn.close();
              } catch (SQLException ex) {
                  JOptionPane.showMessageDialog(null, ex);
              }
           
           aUserNotify.setText(null);
           aNameNotify.setText(null);
           
           
       }
       
       else{
                aUserNotify.setText("user name >3 and no Uppercase");
           aNameNotify.setText("name alow only char and space");
       }
       
       
        //Create a Connection
        
            
        
        
        
        
    }//GEN-LAST:event_BRegActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AName;
    private javax.swing.JPasswordField APass;
    private javax.swing.JTextField AUser;
    private javax.swing.JButton BCancel;
    private javax.swing.JButton BReg;
    private javax.swing.JButton BReset;
    private javax.swing.JLabel PassInfo;
    private javax.swing.JLabel aNameNotify;
    private javax.swing.JLabel aUserNotify;
    private javax.swing.JLabel back;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
