/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurent;

import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author SYSTEM
 */
public class EmpRegistration extends javax.swing.JInternalFrame {
              public Connection conn=null;
              public Statement st;
    /**
     * Creates new form AdminRegistration
     */
    public EmpRegistration() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NameInfo = new javax.swing.JLabel();
        PassInfo = new javax.swing.JLabel();
        eMail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        eName = new javax.swing.JTextField();
        eUser = new javax.swing.JTextField();
        ePass = new javax.swing.JPasswordField();
        eReset = new javax.swing.JButton();
        eCcancel = new javax.swing.JButton();
        eRegister = new javax.swing.JButton();
        back = new javax.swing.JLabel();

        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1112, 685));

        jPanel1.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel3.setText("Name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(330, 210, 140, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("User Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(330, 280, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Password");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(330, 350, 140, 30);

        NameInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        NameInfo.setForeground(new java.awt.Color(255, 153, 0));
        NameInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(NameInfo);
        NameInfo.setBounds(430, 250, 380, 20);

        PassInfo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        PassInfo.setForeground(new java.awt.Color(255, 153, 0));
        PassInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(PassInfo);
        PassInfo.setBounds(370, 320, 480, 20);

        eMail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(eMail);
        eMail.setBounds(490, 420, 250, 40);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("E-mail");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(330, 420, 140, 30);

        eName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(eName);
        eName.setBounds(490, 210, 250, 40);

        eUser.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(eUser);
        eUser.setBounds(490, 280, 250, 40);

        ePass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(ePass);
        ePass.setBounds(490, 350, 250, 40);

        eReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eReset.setText("Reset");
        eReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eResetActionPerformed(evt);
            }
        });
        jPanel1.add(eReset);
        eReset.setBounds(700, 500, 80, 40);

        eCcancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eCcancel.setText("Cancel");
        eCcancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eCcancelActionPerformed(evt);
            }
        });
        jPanel1.add(eCcancel);
        eCcancel.setBounds(400, 500, 80, 40);

        eRegister.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        eRegister.setText("Register");
        eRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(eRegister);
        eRegister.setBounds(540, 500, 110, 40);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Restaurent/Employee Registration back UPDATE.jpg"))); // NOI18N
        jPanel1.add(back);
        back.setBounds(0, 0, 1112, 685);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 660, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void eCcancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eCcancelActionPerformed
        // TODO add your handling code here:
        
        dispose();
    }//GEN-LAST:event_eCcancelActionPerformed

    private void eResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eResetActionPerformed
        eName.setText(null);
        eUser.setText(null);
        ePass.setText(null);
        PassInfo.setText(null);
        eMail.setText(null);
        NameInfo.setText(null);
    }//GEN-LAST:event_eResetActionPerformed

    private void eRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eRegisterActionPerformed
        String enm=eName.getText();
        String eusr=eUser.getText();
        if(enm.matches("^[a-zA-Z\\s]+")&&eusr.matches("^[a-z0-9._-]{3,}$")){
       
         //Create a Connection
        try{
                Class.forName("com.mysql.jdbc.Driver");
                conn=DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant_management?zeroDateTimeBehavior=convertToNull","root","");
                st=conn.createStatement();
                //JOptionPane.showMessageDialog(null, "Connected");
        }
        catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
        
        }
        
        
        //inserting value

        try {
            String em_name=eName.getText();
            String user=eUser.getText();
            String epass=ePass.getText();
            String email=eMail.getText();
            
            
            String sql = "INSERT INTO `employeer_registration`(name, user_name, password, e_mail)"+ "VALUES (?, ?, ?, ?)";
            PreparedStatement preparedStatement = conn.prepareStatement(sql);
                preparedStatement.setString(1,em_name);
                preparedStatement.setString(2,user);
                preparedStatement.setString(3,epass);
                preparedStatement.setString(4,email);
                
                preparedStatement.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data saved Successfully");
                
                //Reset all textfield
                eName.setText(null);
        eUser.setText(null);
        ePass.setText(null);
        PassInfo.setText(null);
        eMail.setText(null);
        PassInfo.setText(null);
           NameInfo.setText(null);
        
        //close connection
                preparedStatement.close();
            conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
        catch(Exception exx){
          JOptionPane.showMessageDialog(null, exx);

       }
        }
        else{
        PassInfo.setText("user name >3 and no Uppercase");
           NameInfo.setText("name alow only char and space");
        
        }
    }//GEN-LAST:event_eRegisterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NameInfo;
    private javax.swing.JLabel PassInfo;
    private javax.swing.JLabel back;
    private javax.swing.JButton eCcancel;
    private javax.swing.JTextField eMail;
    private javax.swing.JTextField eName;
    private javax.swing.JPasswordField ePass;
    private javax.swing.JButton eRegister;
    private javax.swing.JButton eReset;
    private javax.swing.JTextField eUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
