/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Restaurent;

/**
 *
 * @author SYSTEM
 */
public class RegisteredInfo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AdminRegistration
     */
    public RegisteredInfo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        entityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("restaurant_management?zeroDateTimeBehavior=convertToNullPU").createEntityManager();
        employeerRegistrationQuery = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM EmployeerRegistration e");
        employeerRegistrationList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : employeerRegistrationQuery.getResultList();
        employeerRegistrationQuery1 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM EmployeerRegistration e");
        employeerRegistrationList1 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : employeerRegistrationQuery1.getResultList();
        employeerRegistrationQuery2 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM EmployeerRegistration e");
        employeerRegistrationList2 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : employeerRegistrationQuery2.getResultList();
        employeerRegistrationQuery3 = java.beans.Beans.isDesignTime() ? null : entityManager.createQuery("SELECT e FROM EmployeerRegistration e");
        employeerRegistrationList3 = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : employeerRegistrationQuery3.getResultList();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setOpaque(true);
        setPreferredSize(new java.awt.Dimension(1112, 685));

        org.jdesktop.swingbinding.JTableBinding jTableBinding = org.jdesktop.swingbinding.SwingBindings.createJTableBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, employeerRegistrationList3, jTable1);
        org.jdesktop.swingbinding.JTableBinding.ColumnBinding columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${name}"));
        columnBinding.setColumnName("Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${userName}"));
        columnBinding.setColumnName("User Name");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        columnBinding = jTableBinding.addColumnBinding(org.jdesktop.beansbinding.ELProperty.create("${EMail}"));
        columnBinding.setColumnName("EMail");
        columnBinding.setColumnClass(String.class);
        columnBinding.setEditable(false);
        bindingGroup.addBinding(jTableBinding);
        jTableBinding.bind();
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 893, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(162, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 583, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.util.List<Restaurent.EmployeerRegistration> employeerRegistrationList;
    private java.util.List<Restaurent.EmployeerRegistration> employeerRegistrationList1;
    private java.util.List<Restaurent.EmployeerRegistration> employeerRegistrationList2;
    private java.util.List<Restaurent.EmployeerRegistration> employeerRegistrationList3;
    private javax.persistence.Query employeerRegistrationQuery;
    private javax.persistence.Query employeerRegistrationQuery1;
    private javax.persistence.Query employeerRegistrationQuery2;
    private javax.persistence.Query employeerRegistrationQuery3;
    private javax.persistence.EntityManager entityManager;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
